name: latest release on CLN v24.05

on:
    release:
        types: [published, edited]
    workflow_dispatch:

jobs:
    call-ci:
        uses: ./.github/workflows/ci.yml
        with:
            cln-version: "v24.05"
            pyln-version: "24.05"
            tagged-release: true